### ISSUE TITLE
Mobile Miner Shows Wrong Pool

### ISSUE THREAD

**Issue by PartTimeLegend** [michelem09/minera#118]
I'm mining pool 0, but MM reports pool 4 in my failover list.

**Comment by michelem09** [comment]
I can't understand the problem can you take a screenshot and explain? Do you see the pool list in a different order? I cannot see how to look at the current pool on MM. I can only see the list of pools clicking by "Coins".

**Comment by PartTimeLegend** [comment]
Sorry, this might not have come across particularly well.

My primary pool is `eu.multipool.us` which Minera is reporting that I am mining on.
One of my failover pools is `simplemulti.com`. Even though Minera knows I'm mining `eu.multipool.us` mobile miner always reports that I'm mining `simplemulti.com`.

I contacted MobileMiner and they claim it's the data being posted to them, rather than their error. I looked at their API and it was pretty simple to implement and test, but I have no idea why my Minera controllers are showing the wrong pool. I tried reimaging them to no avail and tried other controller software that worked fine.

**Comment by michelem09** [comment]
What's the pools order in Minera settings (NOT the dashboard, in the settings page!) Did you select the main pool from the dashboard while running?

**Comment by oakmaster** [comment]
Im having the same problem everthing in minera shows my main pool but in mobileminer it shows a different pool from my list I tried starting with a fresh minera install and it still does it and no matter what backend miner im using

**Comment by michelem09** [comment]
Please can you give me some screenshots?

**Comment by michelem09** [comment]
Nevermind, you are right, I found the bug.
