### ISSUE TITLE
PHP error from latest build using GIT and CGMiner 3.9.0 Bitmine A1

### ISSUE THREAD

**Issue by llabas** [michelem09/minera#120]
Hi,

Just finished a new install but it's not able to pull stats due to the below PHP error.  I have verified CGMiner is working and sharing data (installed Minera on a brand new raspbian build and the original Bitmine build).

It is hashing to Eligus @ 1TH/s,

Looked through the troubleshooting steps and this is what I see in the logs and via: http://10.xx.xx.xx/minera/index.php/app/stats

<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined variable: pools</p>
<p>Filename: models/util_model.php</p>
<p>Line Number: 254</p>

</div>{"error":true,"altcoins_rates":{"132":{"DOGE":{"primaryname":"Dogecoin","secondaryname":"BitCoin","primarycode":"DOGE","secondarycode":"BTC","label":"DOGE\/BTC","price":"0.00000064","time":1423339207}},"155":{"DRK":{"primaryname":"DarkCoin","secondaryname":"BitCoin","primarycode":"DRK","secondarycode":"BTC","label":"DRK\/BTC","price":"0.00810993","time":1423339209}},"3":{"LTC":{"primaryname":"LiteCoin","secondaryname":"BitCoin","primarycode":"LTC","secondarycode":"BTC","label":"LTC\/BTC","price":"0.00800980","time":1423339210}}}}

**Comment by michelem09** [comment]
Hello,
thanks for the feedback, can I ask you a question? Did you install Minera
"manually" cloning the master Git?
I think I found the problem but I'd like to know this.

**Comment by michelem09** [comment]
I should fixed the bug, you need to pull the changes.

cd /var/www/minera
sudo git fetch --all
sudo git reset --hard origin/master

Please let me know.
Thanks

**Comment by llabas** [comment]
Hi Michael,

Yes I followed the manual instructions you have and cloned the git repo.

TTFN,
Larry
-----------------------------------
http://www.linkedin.com/in/llabas

**Comment by llabas** [comment]
Thanks.

I will do tomorrow afternoon and will let you know.

TTFN,
Larry
-----------------------------------
http://www.linkedin.com/in/llabas

**Comment by llabas** [comment]
Hi,

That helped.  I'm not getting the PHP error anymore however its now reporting that it cannot connect to my minerd on 127.0.0.1:4028.

I've verified it's running and the port is open.   I'm going to switch it from just using 127.0.0.1 using --api-listen to --api-network and see what happens.

On the PHP issue I now see data from:  http://10.50.254.231/minera/index.php/app/stats
{"notrunning":true,"altcoins_rates":{"132":{"DOGE":{"primaryname":"Dogecoin","secondaryname":"BitCoin","primarycode":"DOGE","secondarycode":"BTC","label":"DOGE\/BTC","price":"0.00000064","time":1423438148}},"155":{"DRK":{"primaryname":"DarkCoin","secondaryname":"BitCoin","primarycode":"DRK","secondarycode":"BTC","label":"DRK\/BTC","price":"0.00822000","time":1423438150}},"3":{"LTC":{"primaryname":"LiteCoin","secondaryname":"BitCoin","primarycode":"LTC","secondarycode":"BTC","label":"LTC\/BTC","price":"0.00802973","time":1423438153}}}}

but now am getting the following on the dashboard:

Warning!
It seems your minerd is not running, please try to start it or review your settings.

Might be related to something that I will open another issue for.

Nmap scan report for 10.50.254.231
Host is up (0.00082s latency).
PORT     STATE SERVICE
4028/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds

**Comment by llabas** [comment]
Hi,

The other issue was a configuration error.  I had to reinstall after performing an apt-get update and forgot to turn on the Miner Superuser option.

It's on and the miner is running but Minera is not pulling any stats from it.

root     14089     1  0 15:42 ?        00:00:00 /usr/bin/SCREEN -dmS cgminer-3.9.0 /var/www/minera/minera-bin/custom/cgminer-3.9.0 --A1Pll1 1000 --A1Pll2 1000 --A1Pll3 1000 --A1Pll4 1000 --A1Pll5 1000 --api-listen --cs 8 --stmcu 0 -T --diff 11 --api-network -c /var/www/minera/conf/miner_conf.json

Starting Nmap 6.00 ( http://nmap.org ) at 2015-02-08 15:43 PST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00043s latency).
PORT     STATE SERVICE
4028/tcp open  unknown

From the main log file, I did turn on a donation time.  Let me try turning it off.

root@cm0dragon00:/var/log/minera# tail log-2015-02-08.php 
ERROR - 2015-02-08 15:51:03 --> Storing stats...
ERROR - 2015-02-08 15:51:03 --> Called Minerd with command: {"command":"summary+devs+pools"}
ERROR - 2015-02-08 15:51:03 --> Severity: Notice  --> Undefined variable: poolDonationId /var/www/minera/application/models/util_model.php 644
ERROR - 2015-02-08 15:51:03 --> Severity: Warning  --> Creating default object from empty value /var/www/minera/application/models/util_model.php 644
ERROR - 2015-02-08 15:51:03 --> Delta Stats stored as: {"timestamp":1423439463,"pool_hashrate":0,"hashrate":0,"avg_freq":0,"accepted":0,"errors":0,"rejected":0,"shares":0,"last_share":0}
ERROR - 2015-02-08 15:51:03 --> Total Stats stored as: {"timestamp":1423439463,"pool_hashrate":0,"hashrate":0,"avg_freq":0,"accepted":0,"errors":0,"rejected":0,"shares":0,"last_share":0}
ERROR - 2015-02-08 15:51:03 --> Severity: Notice  --> Undefined variable: totalHashrate /var/www/minera/application/controllers/app.php 1090
ERROR - 2015-02-08 15:51:03 --> Severity: Notice  --> Undefined variable: totalDevices /var/www/minera/application/controllers/app.php 1090
ERROR - 2015-02-08 15:51:03 --> --- END CRON TASKS (0.19 secs) ---
ERROR - 2015-02-08 15:51:13 --> Called Minerd with command: {"command":"summary+devs+pools"}

**Comment by llabas** [comment]
With donations turned off, same errors so I'll turn it back on.

ERROR - 2015-02-08 15:54:14 --> Called Minerd with command: {"command":"summary+devs+pools"}
ERROR - 2015-02-08 15:54:14 --> Severity: Notice  --> Undefined variable: poolDonationId /var/www/minera/application/models/util_model.php 644
ERROR - 2015-02-08 15:54:14 --> Severity: Warning  --> Creating default object from empty value /var/www/minera/application/models/util_model.php 644
ERROR - 2015-02-08 15:54:14 --> Delta Stats stored as: {"timestamp":1423439654,"pool_hashrate":0,"hashrate":0,"avg_freq":0,"accepted":0,"errors":0,"rejected":0,"shares":0,"last_share":0}
ERROR - 2015-02-08 15:54:14 --> Total Stats stored as: {"timestamp":1423439654,"pool_hashrate":0,"hashrate":0,"avg_freq":0,"accepted":0,"errors":0,"rejected":0,"shares":0,"last_share":0}
ERROR - 2015-02-08 15:54:14 --> Severity: Notice  --> Undefined variable: totalHashrate /var/www/minera/application/controllers/app.php 1090
ERROR - 2015-02-08 15:54:14 --> Severity: Notice  --> Undefined variable: totalDevices /var/www/minera/application/controllers/app.php 1090
ERROR - 2015-02-08 15:54:14 --> --- END CRON TASKS (12.11 secs) ---

**Comment by michelem09** [comment]
mmm, that's weird, it seems your Cgminer is running but isn't doing nothing, we need more info. The PHP warnings are normal because it can't get the stats needed by Minera but it seems running:

You can try these:

1- SSH into Minera and try doing "screen -r" to bring up the screen session of cgminer and look what it says

2- Go to the dashboard and look below for the miner log, read it probably there is something wrong there.

Please let me know, I'd really like to fix this.
Thanks!

**Comment by michelem09** [comment]
I can see you are using a custom miner, so we definetely have to look at the cgminer logs, because I'm afraid the custom miner isn't working as it should.
Then, why do you use a custom miner? The latest Cgminer (Official) should support well Bitmine A1, you only need to rebuild the cgminer binary with Bitmine support.

Please try this:

* SSH into Minera and go to /var/www/minera
* Open the file build_miner.sh
* Change the variable CGMINER_CONFIG with this: ```CGMINER_CONFIG="--enable-bitmine_A1"``` (or copy/paste this http://pastebin.com/raw.php?i=8B71w2MS)
* Run the build script with: ```./build_miner.sh cgminer```

Remember to select the official CGminer from your preferred miner software settings.

**Comment by llabas** [comment]
Hi Michael,

It is hashing. When I start it manually it creates output and logs.

When I use the'easy2 mine web interface it shows stats.

I will send you some samples tonight PST.

TTFN,
Larry
-----------------------------------
http://www.linkedin.com/in/llabas

**Comment by michelem09** [comment]
Please try also to look at the cgminer original stats pointing your browser here:

http://<minera-ip>/minera/index.php/app/api?command=miner_stats

These are the original stats Minera gets from CGminer at 127.0.0.1:4028 (then it parses them to be compatible to Minera).

**Comment by llabas** [comment]
Thanks n

I will do tonight and send you the output.

As an Fyi this is a dragon miner 1000 I bought off eBay.

I have tried the latest included cgminer but it does not fully see my boards and won't mine.  I spent half the time trying to get it to work and may open a ticket there also.

TTFN,
Larry
-----------------------------------
http://www.linkedin.com/in/llabas

**Comment by llabas** [comment]
Hi,

This is what I get when I run the miner_stats:

http://10.50.254.231/minera/index.php/app/api?command=miner_stats
{"STATUS":[{"STATUS":"E","When":1423549628,"Code":14,"Msg":"Invalid command","Description":"cgminer 3.9.0"}],"id":1,"original_pools":false,"pools":[]}

It's running on the same web server as the original which returns:

http://10.50.254.231/miner.php?ref=0&pg=Pools

Date: 22:28:32 9-Feb-2015 UTC-08:00
Rig	STATUS	Description	When	API	CGMiner
	S	cgminer 3.9.0	22:28:32 9-Feb-2015 UTC-08:00	2.0	3.9.0
 
Rig	Elapsed	MHS av	Blks	Accepted	Rej	Utility	HW Errs	Net Blks	Work Utility
	4m 07s	1,031,324.76	0	180	1	43.70/m	0	2	101.47/m
Σ	 	1,031,324.76	0	180	1	43.70/m	0	 	101.47/m
 
 	URL	Diff Acc	Diff Rej	Stratum	StrAct	GBT	TSent	BSent	NSent	TRecv	BRecv	NRecv
 	http://stratum.mining.eligius.st:3334	55,295.16	511.99	true	true	false	185	26,634	27,427	195	52,686	52,686
 	stratum+tcp://us1.ghash.io:3333	0	0	true	false	false	2	145	145	6	2,459	2,459
Σ	 	55,295.16	511.99	 	 	 	187	26,779	27,572	201	55,145	55,145

**Comment by michelem09** [comment]
And here is the problem!

Well, I really don't know why your cgminer should throw that error but I'm sorry I can't do anything for that because it's not a Minera problem, it's CGminer or that custom fork.

From the official API readme:

[...] If you request a command that can't be used due to requiring parameters, a command that isn't a report, or an invalid command, you'll get an 'E' STATUS for that one but it will still attempt to process all other commands supplied [...]

It's possible that CGminer fork has something changed from official one and does not permit the API to work correctly or to be requested in the official way.

I'm sorry but I really can't do anything, my recommendation is that you try the official CGminer with Bitman support (you need to recompile it as I said you before).

I'm going to close this because it's not related to Minera, but please feel free to add comments, I will support you if you need.

**Comment by llabas** [comment]
Hi Michael,

I have been trying the official fork and using your build script however
the issue is that it will not see the ASICs (no devices).   I'm going to
keep trying as it's been a struggle with iv 4.0.  First it would not see
any of the boards.  Now I've gotten it to a point where it see's something
for the A1 chips but not the controller board.

Is the APO readme for v4.0 or all versions?

Mind if I suggest that instead of saying minerd not running perhaps it say
"not a supported version" on the stats page?

If you dont mind I'm going to keep digging into it as the miner seems to be
standard 3.9.0 in other aspects.  Maybe there's some minor detail, switch
or something else needed.

Do you know if anyone else using the Dragon miner 1000 th/s boxes use
Minera?

TTFN,
Larry A. LaBas

On Tue, Feb 10, 2015 at 12:46 AM, Michele Marcucci <notifications@github.com

**Comment by michelem09** [comment]
In the next version of Minera errors from miner daemon will be handle differently with more details as you said, I was working on that yet.

Can you try running this from the terminal? (stop any other miner running before)

```/var/www/minera/minera-bin/custom/cgminer-3.9.0 --A1Pll1 1000 --A1Pll2 1000 --A1Pll3 1000 --A1Pll4 1000 --A1Pll5 1000 --api-listen --api-network -c /var/www/minera/conf/miner_conf.json```

Then let me know if devices are detected and it's hashing.

If yes, try to look at the miner stats page: http://<ip>/minera/index.php/app/api?command=miner_stats

Then please give me also the /var/www/minera/conf/miner_conf.json content (you can omit the pool details)

Other things you can try:

* run the cgminer command as root (put "sudo" before the command or do "sudo -s" and then the command)
* try to add "W:10.0.0.0/16" in the settings page in "API Allow" (this shouldn't be needed but try)

Please, let me know.

**Comment by llabas** [comment]
Thanks.

I will do so tonight.

The custom one does work with command below using sudo and it does hash.  I will send a sample tonight.

When I use the miner build script it seems v 4 changed the A1P1 command to the bitminer-a1 variables and I am playing with those to see if I can get the git version to work.

I do appreciate your help and efforts.

TTFN,
Larry
-----------------------------------
http://www.linkedin.com/in/llabas
