### ISSUE TITLE
Feature Request: Hostname Change

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#121]
Feature Request: Hostname change within web configuration - settings page

Workaround:
1. SSH in
2. `sudo vi /etc/hostname` and erase minera and make ti whatever name you want
3. `sudo vi /etc/hosts` and erase minera next to 127.0.0.1 and make it the same name as above
4. Reboot Minera (technically you can reboot a service, but I just reboot the whole device)

**Comment by michelem09** [comment]
I simply do a `sudo hostname <hostname>`, this works well without any reboot.
In /etc/hosts there aren't reference to Minera only to localhost so I will keep that, if someone need deeper conf it's better he/she does it by SSH.
Done and ready for next release.
