### ISSUE TITLE
Web Password Change Error and Suggestion

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#123]
I generated a strong password for the minera web console (`Y75R&ASz$owd`) and the password saved.  However I could never login again.

Could you add a check on the password in Minera to ensure if it is an unsupported password then it would not let you use it?

Also as a suggestion for the password change section in settings, for security, could you make it ask for the old password to ensure the user knows the old password before changing to the new one?

To make things even more secure, each time you save, could it ask you to verify the current web password?

**Comment by michelem09** [comment]
This is a bug, I'm fixing it.
For the current password request, yes it's possible.

**Comment by PartTimeLegend** [comment]
>I generated a strong password for the minera web console (Y75R&ASz$owd)

Not so secure anymore. :stuck_out_tongue_winking_eye:

**Comment by computeronix** [comment]
Just an example password :). But true :)

Bill

Sent from my iPhone

On Mar 23, 2015, at 8:12 AM, Antony Bailey <notifications@github.com<mailto:notifications@github.com>> wrote:


I generated a strong password for the minera web console (Y75R&ASz$owd)

Not so secure anymore. [:stuck_out_tongue_winking_eye:]

-

**Comment by michelem09** [comment]
As workaround in the mean time I release the new version you should use a combination of letters/numbers only in your passwords. No symbols of any kind.
