### ISSUE TITLE
Custom Miner API Error Stats

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#125]
I installed the custom miner (https://github.com/dtbartle/cgminer-gc3355) and it runs fine within Minera.  However I keep the following error on the dashboard even though the API is enabled.

`I can't get the stats from your minerd. Please try to refresh the page or check your settings (minerd API must listen on 127.0.0.1:4028`

Are there any logs or test sites to review any errors or API tests in Minera?

**Comment by michelem09** [comment]
You can try check:

* miner stats page http://<ip>/minera/index.php/app/api?command=miner_stats
* miner log application/logs/<miner>.log
* minera log application/logs/log-2015-<MM>-<DD>.php

Can you give me the command line you use to start that miner?

**Comment by computeronix** [comment]
Command:
--gridseed-options=baud=115200,freq=1163 --hotplug 30 --retries=1

This is the command generated by minera (I have superuser turned on as it will not work without it)
/usr/bin/screen -dmS cgminer-dtbartle-gc3355 /var/www/minera/minera-bin/custom/cgminer-dtbartle-gc3355 --gridseed-options=baud=115200,freq=1163 --hotplug 30 --retries=1 -c /var/www/minera/conf/miner_conf.json

I have also opened up issue (#127) as if you want to specify a script instead of a direct binary you cannot currently do this because -c xxxx is appended to the command by minera.

I have also opened up issue (#124) because currently if you use a custom miner, there is no logging that is appended to the command so that the dashboard logs do not work.

As mentioned the miner starts and in the console window it shows it is enabling API (as the JSON file tells it to).  I have tried manually specifying the API commands and those did not change anything.

I am checking the three directories now for logs...

**Comment by computeronix** [comment]
http://x.x.x.x/minera/index.php/app/api?command=miner_stats  outputs

`{"STATUS":[{"STATUS":"E","When":1425911903,"Code":14,"Msg":"Invalid command","Description":"cgminer 3.7.2"}],"id":1,"original_pools":false,"pools":[]}`

Logs output:

/var/www/minera/application/logs $ tail log-2015-03-09.php ERROR - 2015-03-09 10:39:01 --> Storing stats...
ERROR - 2015-03-09 10:39:01 --> Called Minerd with command: {"command":"summary+devs+pools"}
ERROR - 2015-03-09 10:39:01 --> Severity: Notice  --> Undefined variable: poolDonationId /var/www/minera/application/models/util_model.php 644
ERROR - 2015-03-09 10:39:01 --> Severity: Warning  --> Creating default object from empty value /var/www/minera/application/models/util_model.php 644
ERROR - 2015-03-09 10:39:01 --> Delta Stats stored as: {"timestamp":1425911941,"pool_hashrate":0,"hashrate":0,"avg_freq":0,"accepted":0,"errors":0,"rejected":0,"shares":0,"last_share":0}
ERROR - 2015-03-09 10:39:01 --> Total Stats stored as: {"timestamp":1425911941,"pool_hashrate":0,"hashrate":0,"avg_freq":0,"accepted":0,"errors":0,"rejected":0,"shares":0,"last_share":0}
ERROR - 2015-03-09 10:39:01 --> Severity: Notice  --> Undefined variable: totalHashrate /var/www/minera/application/controllers/app.php 1090
ERROR - 2015-03-09 10:39:01 --> Severity: Notice  --> Undefined variable: totalDevices /var/www/minera/application/controllers/app.php 1090
ERROR - 2015-03-09 10:39:01 --> Called Minerd with command: {"command":"summary+devs+pools"}


Any ideas?  cgminer-dtbartle-gc3355 is running off 3.7.2

The reason I am using this for gc3355 over the dmaxl (I am using dmaxl on another rig) is because voltage modified gc3355 works amazingly off dtbartle.  If I use dmaxl they give hardware errors left and right.

**Comment by michelem09** [comment]
Did you turned on API-allow option for your subnet?

**Comment by computeronix** [comment]
Yes, I even modified the command line to this and it still does gives the same error

10.10.10.0 /24 is my local subnet

--api-allow W:127.0.0.1,W:10.10.10/24 --gridseed-options=baud=115200,freq=1163 --hotplug 30 --retries=1

**Comment by michelem09** [comment]
try to connect via telnet from Minera system, do:

    telnet 127.0.0.1 4128 <enter>
    {"command":"summary"} <enter>

Also, check if port is open:

    netstat -an |grep 4128

Please, give me results.

**Comment by computeronix** [comment]
Installed telnet client putty
`apt-get install putty telnet`

Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

netstat -an |grep 4128
Shows nothing

hmmm, appears API is not running even though the logs show it is starting on 4128, checking a few more things with the miner

Do you know with the generic version of cgminer if API needs to be added to the ,/configure command?  I don't think it does, but thought I would ask.

**Comment by michelem09** [comment]
Try to add `--api-listen` to the miner options

**Comment by computeronix** [comment]
One sec, backing up  you mentioned 4128 when 4028 is the default port :)

Going back to 4028


minera@xxx ~ $ telnet 127.0.0.1 4028
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
{"command":"summary"}
{"STATUS":[{"STATUS":"S","When":1425918866,"Code":11,"Msg":"Summary","Description":"cgminer 3.7.2"}],"SUMMARY":[{"Elapsed":86,"MHS av":5.05,"MHS 5s":4.89,"Found Blocks":0,"Getworks":10,"Accepted":1,"Rejected":0,"Hardware Errors":0,"Utility":0.70,"Discarded":18,"Stale":0,"Get Failures":0,"Local Work":138,"Remote Failures":0,"Network Blocks":3,"Total MH":433.4054,"Work Utility":0.70,"Difficulty Accepted":1024.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Best Share":1882,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Pool Rejected%":0.0000,"Pool Stale%":0.0000}],"id":1}Connection closed by foreign host



minera@xxx ~ $ netstat -an |grep 4028
tcp        0      0 0.0.0.0:4028            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:4028          127.0.0.1:53860         TIME_WAIT
tcp        0      0 127.0.0.1:4028          127.0.0.1:53861         TIME_WAIT
tcp        0      0 127.0.0.1:4028          127.0.0.1:53877         TIME_WAIT
tcp        0      0 127.0.0.1:4028          127.0.0.1:53873         TIME_WAIT
tcp        0      0 127.0.0.1:4028          127.0.0.1:53878         TIME_WAIT
tcp        0      0 127.0.0.1:4028          127.0.0.1:53862         TIME_WAIT

**Comment by michelem09** [comment]
Yeah, sorry, my bad.

So, summary command works, not try via telnet something like:

    {"command":"summary+dev"}

and

    {"command":"summary+dev+pools"}

**Comment by computeronix** [comment]
minera@gcm-bulldozer ~ $ telnet 127.0.0.1 4028
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
{"command":"summary+dev"}
{"STATUS":[{"STATUS":"E","When":1425919563,"Code":14,"Msg":"Invalid command","Description":"cgminer 3.7.2"}],"id":1}Connection closed by foreign host.
minera@gcm-bulldozer ~ $ {"command":"summary+dev+pools"}
-bash: {command:summary+dev+pools}: command not found

Looks like it did not like the dev+pools

**Comment by computeronix** [comment]
This is the actual error, apprently the connection closes after each command :)

telnet 127.0.0.1 4028
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
{"command":"summary+dev+pools"}
{"STATUS":[{"STATUS":"E","When":1425919766,"Code":14,"Msg":"Invalid command","Description":"cgminer 3.7.2"}],"id":1}Connection closed by foreign host.

and if I could read, it did not like the first command either, looking through the documentation
https://github.com/dtbartle/cgminer-gc3355/blob/master/API-README

it looks like it likes
{"command":"devs"}


{"STATUS":[{"STATUS":"S","When":1425919895,"Code":9,"Msg":"10 ASC(s) - ","Description":"cgminer 3.7.2"}],"DEVS":[{"ASC":0,"Name":"GSD","ID":0,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":6,"Rejected":0,"Hardware Errors":0,"Utility":0.95,"Last Share Pool":2,"Last Share Time":1425919864,"Total MH":185.6944,"Diff1 Work":6,"Difficulty Accepted":2481.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":315.00000000,"No Device":false,"Last Valid Work":1425919864,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":1,"Name":"GSD","ID":1,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":11,"Rejected":0,"Hardware Errors":0,"Utility":1.75,"Last Share Pool":2,"Last Share Time":1425919824,"Total MH":185.7194,"Diff1 Work":11,"Difficulty Accepted":3859.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":315.00000000,"No Device":false,"Last Valid Work":1425919824,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":2,"Name":"GSD","ID":2,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":4,"Rejected":0,"Hardware Errors":0,"Utility":0.63,"Last Share Pool":2,"Last Share Time":1425919804,"Total MH":185.7394,"Diff1 Work":4,"Difficulty Accepted":1260.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":315.00000000,"No Device":false,"Last Valid Work":1425919804,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":3,"Name":"GSD","ID":3,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":0,"Rejected":0,"Hardware Errors":1,"Utility":0.00,"Last Share Pool":-1,"Last Share Time":0,"Total MH":185.7047,"Diff1 Work":0,"Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":0.00000000,"No Device":false,"Last Valid Work":1425919507,"Device Hardware%":100.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":4,"Name":"GSD","ID":4,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":5,"Rejected":0,"Hardware Errors":0,"Utility":0.79,"Last Share Pool":2,"Last Share Time":1425919815,"Total MH":185.8730,"Diff1 Work":5,"Difficulty Accepted":2993.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":315.00000000,"No Device":false,"Last Valid Work":1425919815,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":5,"Name":"GSD","ID":5,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":0,"Rejected":0,"Hardware Errors":0,"Utility":0.00,"Last Share Pool":-1,"Last Share Time":0,"Total MH":185.7947,"Diff1 Work":0,"Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":0.00000000,"No Device":false,"Last Valid Work":1425919508,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":6,"Name":"GSD","ID":6,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":0,"Rejected":0,"Hardware Errors":0,"Utility":0.00,"Last Share Pool":-1,"Last Share Time":0,"Total MH":185.7913,"Diff1 Work":0,"Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":0.00000000,"No Device":false,"Last Valid Work":1425919509,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":7,"Name":"GSD","ID":7,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":0,"Rejected":0,"Hardware Errors":1,"Utility":0.00,"Last Share Pool":-1,"Last Share Time":0,"Total MH":185.8314,"Diff1 Work":0,"Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":0.00000000,"No Device":false,"Last Valid Work":1425919509,"Device Hardware%":100.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":8,"Name":"GSD","ID":8,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":0,"Rejected":0,"Hardware Errors":1,"Utility":0.00,"Last Share Pool":-1,"Last Share Time":0,"Total MH":185.9127,"Diff1 Work":0,"Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":0.00000000,"No Device":false,"Last Valid Work":1425919510,"Device Hardware%":100.0000,"Device Rejected%":0.0000,"Device Elapsed":378},{"ASC":9,"Name":"GSD","ID":9,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":0.49,"MHS 5s":0.49,"Accepted":8,"Rejected":0,"Hardware Errors":0,"Utility":1.27,"Last Share Pool":2,"Last Share Time":1425919807,"Total MH":185.9004,"Diff1 Work":8,"Difficulty Accepted":3426.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":315.00000000,"No Device":false,"Last Valid Work":1425919807,"Device Hardware%":0.0000,"Device Rejected%":0.0000,"Device Elapsed":378}],"id":1}Connection closed by foreign host.

and it likes

{"command":"pools"}
{"STATUS":[{"STATUS":"S","When":1425919961,"Code":7,"Msg":"3 Pool(s)","Description":"cgminer 3.7.2"}],"POOLS":[{"POOL":0,"URL":"stratum+tcp://us-east.multipool.us:7777","Status":"Dead","Priority":0,"Quota":1,"Long Poll":"N","Getworks":1,"Accepted":0,"Rejected":0,"Works":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"gocloudmine.bulldozer","Last Share Time":0,"Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"us-east.multipool.us","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000},{"POOL":1,"URL":"stratum+tcp://us-west.multipool.us:7777","Status":"Dead","Priority":1,"Quota":1,"Long Poll":"N","Getworks":1,"Accepted":0,"Rejected":0,"Works":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"gocloudmine.bulldozer","Last Share Time":0,"Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"us-west.multipool.us","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000},{"POOL":2,"URL":"stratum+tcp://us.clevermining.com:3333","Status":"Alive","Priority":2,"Quota":1,"Long Poll":"N","Getworks":42,"Accepted":40,"Rejected":0,"Works":442,"Discarded":80,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"daffe7f89e0770ea90af773a0cebae2eaace73e2","Last Share Time":1425919949,"Diff1 Shares":40,"Proxy Type":"","Proxy":"","Difficulty Accepted":15909.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":315.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"us.clevermining.com","Has GBT":false,"Best Share":13785,"Pool Rejected%":0.0000,"Pool Stale%":0.0000}],"id":1}Connection closed by foreign host.

by themselves

**Comment by michelem09** [comment]
This is a problem because a lot of miners (bfgminer/cgminer officials at least) has the possibility to concat the commands, it's weird this fork cannot do it and there isn't a simple workaround in Minera to get them separately. 
You should try to open an issue here: https://github.com/dtbartle/cgminer-gc3355

**Comment by computeronix** [comment]
Ok will check this out, thanks so much for the assistance!

**Comment by michelem09** [comment]
You're welcome! I'm going to close this, but feel free to reopen it if you need.

P.S.
In the next days I will answer you for the feature requests you sent
