### ISSUE TITLE
Feature Request: Support Dashing Mining Dashboard Agent

### ISSUE THREAD

**Issue by ghost** [michelem09/minera#126]
Feature Request: Support the dashing-mining-dashing agent

Agent Location: https://github.com/suda/dashing-mining-agent

The dashing agent is now coded for the Rapsberry PI (and minera) compatibility.

all the install/config settings are documented within the readme.  It would be neat if this was coded into the web interface to be able to edit those settings as needed and turn on and off the agent as needed.

**Comment by computeronix** [comment]
The agent, in addition to supporting cgminer, now supports cpuminer
