### ISSUE TITLE
Custom Miner Script

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#127]
Currently you cannot specify a custom miner script and can only specify a binary directly in minera.  This is due to the fact that ` -c /var/www/minera/conf/miner_conf.json` is appended automatically to any manual commands you enter.  Also Manual options textbox is a required field.

Can you adjust the following
1. Make manual options and optional field
2. Add a slider (yes/no) for the appending of  `-c /var/www/minera/conf/miner_conf.json`

After those two items are fixed then you should be able to specify a script instead of a binary within the custom miners directory (similar to your script outside the custom directory for cgminer :) )

**Comment by michelem09** [comment]
I put a toggle switch to append or not the JSON conf. It should be enough I think, because you can always switch from Guided to Manual options.
