### ISSUE TITLE
Correct BFGMiner fix - 5.1.0 is now the latest

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#130]
FYI, the dropdown box shows BFGMiner 4.x...BFGMiner is now on 5.1 so if you could change the version to 5.xx and ensure that is the latest build being used

**Comment by computeronix** [comment]
Also on the next release of minera if you could run the build bfgminer current version in minera is 5.0.0-6.

When I run the build script it fails with the following

fatal: The remote end hung up unexpectedly
Clone of 'git://gitorious.org/bitcoin/libblkmaker.git' into submodule path 'libblkmaker' failed

Also when you re-run the build script -> it fails saying the miner already exists in the src directory.  Can you have it remove those files by mistake and then re-build whenever the script is run?

Thanks and as usual amazing program!!

**Comment by luke-jr** [comment]
The libblkmaker issue is upstream with BFGMiner, see https://github.com/luke-jr/bfgminer/issues/608

**Comment by computeronix** [comment]
Thanks Luke nice call!
