### ISSUE TITLE
Minera Pool through a Proxy

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#139]
I am using https://github.com/Stratehm/stratum-proxy and pointing all my Minera devices to this pool.

However, in the Minera dashboard even though accepted hashrates are going, Minera shows the pool as Dead

Any ideas?

![screen shot 2015-05-03 at 11 00 31 pm](https://cloud.githubusercontent.com/assets/11186939/7448460/4b1c8a20-f1e8-11e4-87b7-0b13530fbd2a.png)

**Comment by michelem09** [comment]
Is the pool port completely public to the internet? Can you try this from your Minera and paste the output:

nmap -p<POOL_PORT> <POOL_HOST>

**Comment by computeronix** [comment]
No it is internal lan accessible only --- from the proxy it then goes out to the internet as needed


Results of nmap from minera

nmap -p


Error requires argument



Bill
________________________________

**Comment by michelem09** [comment]
You have to put your pool url and port to the nmap command, I cannot know that because you obscured it in the picture.

**Comment by michelem09** [comment]
I tried to use https://github.com/Stratehm/stratum-proxy with my Minera and it works well, can I know the miner software you are using?

**Comment by computeronix** [comment]
BFGMiner, latest compiled version


Bill
________________________________

**Comment by michelem09** [comment]
Check your proxy log, because it's easy the problem is there, the proxy must have at least one pool enabled and connected to be considered reachable (alive) by a miner.
I'm closing this because I doubt it's a Minera issue, but feel free to reopen if needed.
