### ISSUE TITLE
Minera Build Miner Bug

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#140]
When I go to upgrade the miner (bfgminer, lets say) the following error occurs

sudo ./build_miner.sh bfgminer

Cloning repo https://github.com/luke-jr/bfgminer.git into /var/www/minera/minera-bin/src/bfgminer
fatal: destination path '/var/www/minera/minera-bin/src/bfgminer' already exists and is not an empty directory.

So I go into minera-bin/src and remove the bfgminer folder and this resolves the issue as a workaround

**Comment by michelem09** [comment]
Yes, thanks I need to fix this.
