### ISSUE TITLE
Message: Only variable references should be returned by reference

### ISSUE THREAD

**Issue by t0mtaylor** [michelem09/minera#141]
http://stackoverflow.com/questions/28348879/only-variable-references-should-be-returned-by-reference-codeigniter

A PHP Error was encountered

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 257

Code Igniter should be upgraded, or you can follow the temporary change:
	
Edit filename: core/Common.php, line number: 257

Before

return $_config[0] =& $config; 

After

$_config[0] =& $config;
return $_config[0];

**Comment by michelem09** [comment]
Thanks for reporting that, I will do something for next release.

**Comment by t0mtaylor** [comment]
Thanks! :) :+1:
