### ISSUE TITLE
Login Not Found

### ISSUE THREAD

**Issue by farfeduc** [michelem09/minera#142]
Hello,

I just installed your app on my little debian with nginx and when I connect on the login page and type "minera" on the input it redirects my to : myip/minera/index.php/app/login and displays : 404 not found.

Any idea where this is coming from ?

Thanks in advance

**Comment by michelem09** [comment]
Do you use Nginx+PHP5-FPM?
You need to have something like this: http://wiki.nginx.org/Codeigniter

**Comment by farfeduc** [comment]
Thanks !
I'll try to see if I have this
Le 13 mai 2015 17:34, "Michele Marcucci" <notifications@github.com> a
écrit :

**Comment by michelem09** [comment]
Please refer to this wiki page to install Minera on a Debian system: https://github.com/michelem09/minera/wiki/Getting-started#manual-install
Feel free to reopen if you need.
