### ISSUE TITLE
bfgminer current version below 5.x

### ISSUE THREAD

**Issue by computeronix** [michelem09/minera#145]
In the GUI the BFGminer is listed as 5.x however when running version, the below is displayed
bfgminer 4.8.0-34-g9c71295

even running the upgrade script only keeps it at v4  Any scripts or commands to move this to 5?  Will it be supported next version?

**Comment by michelem09** [comment]
You have an old version, just update it read here: https://github.com/michelem09/minera/wiki/Local-miners

    cd /var/www/minera
    ./build_miner.sh bfgminer

**Comment by computeronix** [comment]
I used 6.1 img and this is the version that came with it
Also, I performed the script before I posted and the version stayed the exact same

**Comment by michelem09** [comment]
That sounds weird, are you sure you haven't another bfgminer installed in the system? Can you give me the output of this command?

    cd /var/www/minera
    ./minera-bin/bfgminer -V

**Comment by computeronix** [comment]
Checking now, I applied the 6.1 img and applied no special binaries

**Comment by computeronix** [comment]
Interesting...the command shows this however.....

 /var/www/minera $ ./minera-bin/bfgminer -V
bfgminer 5.1.0-36-g8b5d36b
  Lowlevel: ftdi pci pci:uio spi usb vcom 
  Drivers: antminer avalon avalonmm bfx bifury bigpic bitforce bitforce:pci bitfury cairnsmore cointerra drillbit dualminer erupter gridseed hashbusterusb hashfast icarus klondike littlefury modminer proxy proxy:getwork proxy:stratum rockminer twinfury x6500 zeusminer ztex 
  Algorithms: SHA256d scrypt 
  Options: ncurses5 


.....
If I go to /var/www/minera/minera-bin and run bfgminer -V  it shows
bfgminer 4.8.0-34-g9c71295

**Comment by michelem09** [comment]
If you run `bfgminer` without the `./` in front of it you get the system one that should be in /usr/bin/bfgminer.

But Minera doesn't use that, it uses bfgminer in /var/www/minera/minera-bin and as I thought that's updated.

**Comment by computeronix** [comment]
bfgminer does not exist in my /usr/bin directory

if I navigate to /var/www/minera/minera-bin and run just "bfgminer -V" it shows the older one  same if I go to the src folder and review the binary, still old in there too

**Comment by computeronix** [comment]
nvm disregard  I see it now :)

**Comment by michelem09** [comment]
I don't know how to tell you this. If you run bfgminer alone it gets the default one on the default $PATH but Minera doens't use that.

If you navigate into /var/www/minera/minera-bin you HAVE TO run it as `./bfgminer` (check there is `./` that's completely different to run it without) otherwise the system gets that one in the default $PATH.

Wanna see where is it? Run `whereis bfgminer`and you'll see the path of that one.
