### ISSUE TITLE
Adding Multiple Network Miners through import. 

### ISSUE THREAD

**Issue by 9600-** [michelem09/minera#148]
Quick question,
I'd like to have an x86 Minera monitoring about 100 miners. Any way I can upload the miner IPs in bulk? I don't see any flat files with network config data. Are these values stored in redis?

Thanks,
9600

**Comment by michelem09** [comment]
I'm sorry I can't understand. Are you talking about adding/configuring 100 **network** miners?

**Comment by 9600-** [comment]
That is correct, but I believe I just figured out my own way of dealing with the issue. 
Simply restructuring and importing the structured minera-export.json with the added IP addresses works  quite well.

**Comment by michelem09** [comment]
Oh well, very good!
