### ISSUE TITLE
Limit on number of network miners

### ISSUE THREAD

**Issue by 9600-** [michelem09/minera#150]
Hello there,
I can only add 239 network miners. 
When trying to add 240+, the interface allows me to save but the new miners no longer populate the list. 

![network_mon](https://cloud.githubusercontent.com/assets/7446395/10059769/caf251e2-6201-11e5-987a-3ecddb6c1151.PNG)

**Comment by michelem09** [comment]
I will investigate this.

**Comment by michelem09** [comment]
Found the issue, next release will be fixed in the meantime you can do this:

Open file `/etc/php5/fpm/php.ini`
Add this: `max_input_vars = 10000`
Restart Php Fpm: `sudo service php5-fpm restart`
