### ISSUE TITLE
Enhancement / Feature Request: RSS Feed

### ISSUE THREAD

**Issue by cbrightly** [michelem09/minera#151]
I know that JSON is the preferred method for displaying raw statistics / settings and is how the software currently displays that data. Is it possible to have the software render an RSS feed for statistics and settings as well?

**Comment by michelem09** [comment]
How can I put that data in RSS format? Do you have some idea? RSS is to read chronological contents like blog post, timelines, notifications and something like those, I don't think it's a great way to read statistics like those from Minera, but please let me know what you think.

**Comment by cbrightly** [comment]
Well, I suppose JSON format would actually be fine;  I _do_ only need a
snapshot of settings and/or performance, not a timeline.

I am writing an IRC bot that I would like to be able to have fetch specific
fields / variables or all of the data that Minera uses or
calculates via HTTP so that the program can display current mining
information on demand. Ideally I would like to program this  without having
to search strings in large and rather unreadable JSON files and am seeking
alternative approaches and or data file formats to achieve this.

I hope that makes sense... Thoughts?

**Comment by michelem09** [comment]
JSON is the best format you can have to do what you need, there isn't anything better than that. If you have problem reading it just install a browser extension to format/indent it like this: 

https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en

And you'll see how easy and usable it is. You don't need any parser too (for a RSS you need it), don't know what code you are writing but JSON is really easy to be converted in object to play with.

So, my recommendation is to use the Minera JSON, I could add a new one to show you all the settings.

**Comment by cbrightly** [comment]
A JSON displaying the values shown at the top of the dashboard such as
local hashrate, error count and percentage, current pool, etc. would be
amazing to have. Maybe also currently detected devices? An overview of the
most relevant values you might want to show off or check from IRC, for
example? ;) Thanks again for an amazing tool!
