### ISSUE TITLE
Removing or stopping Minera

### ISSUE THREAD

**Issue by 0xicl33n** [michelem09/minera#152]
How is this done? There is literally no documentation on how to stop it from automatically starting up cgminer screen sessions if you have no miners connected to your computer anymore. Stopping lightttpd is not enough. 

The raspi i was using is no longer a miner and it continues to try and mine with no miners connected, id like it to stop doing that because its just wasting cpu power

**Comment by michelem09** [comment]
If there isn't anything connected to the RPI it is not mining. Try to delete everything in `/etc/rc.local` so it shouldn't start anymore after reboot.
If you want you could also remove the entire directory `/var/www/minera`.
