### ISSUE TITLE
Reset to Factory Never Completes on PI

### ISSUE THREAD

**Issue by Nargousias** [michelem09/minera#153]
Using image on a PI.  Was able to change local mining settings.  No longer allows me to save or save & restart.  The Factory Reset is also hanging.  Is there a manual SSH or command prompt fix to perform the same type of reset or should I just start from scratch with a fresh image reload?

**Comment by michelem09** [comment]
Sorry i'm on my vacation, no time/manner to help you.
faster thing you can do is start from scratch with the image

Il giorno mar 26 gen 2016 alle 03:43 Nargousias <notifications@github.com>
ha scritto:

**Comment by michelem09** [comment]
Please look at web console log when you try to do some action (like restart miner) probably you will see a kind of error, please tell me.
Thanks

**Comment by michelem09** [comment]
Closing to lack of informations.
