### ISSUE TITLE
Antminer S7 as Network Miners

### ISSUE THREAD

**Issue by suchpool** [michelem09/minera#154]
Just a simple "bug" I found if you want to call it that way. I guess the API output changed overtime, and the rejection % isn't calculated properly.

For example, on a miner I am seeing over 90% rejected shares while directly in the interface it's 0.2%. Is that something easy to fix? I can probably do it, simply let me know which functions need to be touched. Would also be cool to get the frequency, I know it is available via the API as I'm parsing it in bash for a lot of data.

Thanks!

**Comment by michelem09** [comment]
Can I know the miner software you are using?

You can check a couple of functions:

`getMinerStats` https://github.com/michelem09/minera/blob/master/application/models/util_model.php#L227

And:

`getParsedStats` 
https://github.com/michelem09/minera/blob/master/application/models/util_model.php#L336

**Comment by suchpool** [comment]
It's a straight cgminer with some optimisations by bitmaintech I presume.

I'll see if I can do anything on my end!

Thanks!

On 2016-02-09 11:33, Michele Marcucci wrote:
>
> Can I know the miner software you are using?
>
> You can check a couple of functions:
>
> |getMinerStats| 
> https://github.com/michelem09/minera/blob/master/application/models/util_model.php#L227
>
> And:
>
> |getParsedStats|
> https://github.com/michelem09/minera/blob/master/application/models/util_model.php#L336
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/michelem09/minera/issues/154#issuecomment-181945092>.
>


-- 
-----------------
eth1@suchpool.pw
Administrator

SuchPool.pw Cryptocurrency Pools
http://suchpool.pw

**Comment by AccessDG** [comment]
and this still exists within the software...
