### ISSUE TITLE
custom miner shows offline

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [michelem09/minera#157]
running tpruvot/cpuminer-multi as custom. Note the terminal window `top` output.

![screenshot-minera-20170204](https://cloud.githubusercontent.com/assets/7605896/22622812/d3202acc-eaf1-11e6-8d10-38fc43891b43.png)

Also had to pass all normal cli flags in the config window. Minera did not configure miner with pool/user/pass settings in config section.

Is this normal for custom miners?

**Comment by michelem09** [comment]
No it isn't, please check the miner logs and let me see it.

**Comment by ParaplegicRacehorse** [comment]
Gonna have to wait. OS updates require that I reinstall everything. Maybe it will even fix this error. I'll let you know tomorrow. It's bedtime here.

I wonder if this next install will rewrite my ssh keys again. Grr.

**Comment by michelem09** [comment]
How do you start it? Via Minera or manually?

**Comment by ParaplegicRacehorse** [comment]
The cpuminer? I start via minera. Installing minera ruins my ability to ssh from terminal, which is how I manage the rest of machine. I probably will not reinstall for that reason.

**Comment by ParaplegicRacehorse** [comment]
I just discovered that tprovot/cpuminer-multi, since 1.0.8, has had an API for monitoring. I assume I need to set the IP and port numbers to a range Minera looks for? Will it be the same as for bfgminer and others?

I will probably reinstall and test this out if I can figure out how/where to publish the API in a way Minera can monitor it. As for ssh keys, I'll figure something out. It bothers me a lot that Minera overwrites my existing key but it's not the end of the world. I won't do this today (probably) but I'll let you know what I discover.

**Comment by michelem09** [comment]
I think it uses a different way to get API requests but I'm unable to test it because I'm living abroad for the next months.

**Comment by michelem09** [comment]
Hello,
I have investigare this and I can confirm` cpuminer-multi` works fine on Minera but you have to configure it.
First of all, JSON file doesn't work I don't know why probably it want a different format, so disable it from Minera and put your miner command on Manual Options textarea like this:

`-o stratum+tcp://<pool_url>:<pool_port> -u <pool_user> -p x --api-bind=127.0.0.1:4028`

Note! You have also to use the option `--api-bind` because it runs by default on port `4048` while Minera get by default port `4028`, this is why you didn't see anything in the dashboard.

Please let me know.

**Comment by ParaplegicRacehorse** [comment]
Thanks, Michele. I'm at sea and away from my miners for the rest of the
year, unable to experiment. The API port difference makes sense.

I had to remove Minera from my miners, though. Node is extremely
CPU-intensive, using up about 20% of my CPU cycles just to run it, an
unacceptable loss of hash power for a CPU miner. I'm sure that's different
for recent Intel and AMD processors, but my ARM machines just won't sustain
Node and be profitable.

**Comment by michelem09** [comment]
Oh well RPI cpu isn't so good to ask it a lot of things to do, yes better to put Minera in a desktop or server.
