### ISSUE TITLE
Dockerfile for minera? Minera as a Docker image

### ISSUE THREAD

**Issue by alberttwong** [michelem09/minera#158]
I'd like to request a dockerfile for minera.  Thanks!

**Comment by alberttwong** [comment]
I tried building my own dockerfile and it prompts the mail configuration.  How can we script the entire install and configuration?

**Comment by alberttwong** [comment]
Docker doesn't like
```
[Build]    Run /etc/init.d/lighttpd force-reload to enable changes
[Build]    Reloading web server configuration: lighttpd failed!
```

**Comment by michelem09** [comment]
Look at this: https://github.com/michelem09/minera/pull/155

**Comment by alberttwong** [comment]
So maybe it's me but I don't see a dockerfile in your master branch.

**Comment by michelem09** [comment]
Try now
