### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by mathmatrix828** [michelem09/minera#159]
As I'm sure we're all aware, PHP5 is no longer supported on Ubuntu (specifically, U16.10 is what I'm using). What should I do to make the shift for this product to PHP7?

**Comment by mathmatrix828** [comment]
Currently I'm getting a 503 Service Unavailable message, and the lighttpd error log is giving me

```
2017-03-10 19:33:55: (mod_fastcgi.c.1754) connect failed: No such file or directory on unix:/var/run/php5-fpm.sock·
2017-03-10 19:33:55: (mod_fastcgi.c.3021) backend died; we'll disable it for 1 seconds and send the request to another backend instead: reconnects: 0 load: 1·
2017-03-10 19:33:57: (mod_fastcgi.c.2848) fcgi-server re-enabled: unix:/var/run/php5-fpm.sock
```

**Comment by michelem09** [comment]
Yes you have to switch to PHP7. Try this skipping the Mysql part: https://www.howtoforge.com/tutorial/installing-lighttpd-with-php7-php-fpm-and-mysql-on-ubuntu-16.04-lts/

**Comment by nukepower** [comment]
the way I did it , was edit any minera files or folders that have php5 to php7.0 then it  installs and works  fine but if you don't want to do that i have the files set a side for any install i may do down the road and then copy my edited files in to  minera after i down load it on a clean install Of Ubuntu 16 .. I'll give you a copy of my files you can look them over to see what i did .. and install lighttpd php7.0-cgi like below so far it works on any PI i do it on with Ubuntu 16 installed .


sudo apt-get install -y lighttpd php7.0-cgi
sudo lighty-enable-mod fastcgi-php
sudo lighty-enable-mod fastcgi
sudo service lighttpd force-reload

**Comment by michelem09** [comment]
Thanks I will do something for PHP7.0 asap.
