### ISSUE TITLE
Ads-Free too easy

### ISSUE THREAD

**Issue by mathmatrix828** [michelem09/minera#160]
As a fellow frameworks coder, it took me only a few minutes to go through and make the changes to remove ads. I highly suggest finding another method of determining ads-free status, like checking for some kind of key that's stored.

NOTE: do not ask me for this. I will not be sharing.
P.S. you're using my favorite PHP framework ;) props for this amazing project!

**Comment by michelem09** [comment]
I know and I wrote times ago about this. If you can able to do it good for you but I don't want by now to secure this.
Thanks
