### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by watashimeandeu** [michelem09/minera#161]
Hi,
Since a while ago i can't login. 
As soon i click enter the page refresh to login again.
The browser console:
    Uncaught TypeError: e.data.split is not a function
        at s (button.js:1)

Raspberry Pi 1 Model B, 
Minera 0.7.0

It's better install all again?
Thank you.

**Comment by michelem09** [comment]
Did you try a code update with:

```
cd /var/www/minera
sudo git fetch --all && sudo git reset --hard origin/master
```

Can you check your redis daemon is running?

**Comment by watashimeandeu** [comment]
Already update the code, update and upgrade os, reboot and nothing happens.
Everything seems working fine because is mining to the pool, but no login.
How can i check if redis daemon is running?

**Comment by michelem09** [comment]
do a `redis-cli info`
Then check also you have enough disk space `df -h`
Finally check the logs on `/var/www/minera/application/logs`

**Comment by watashimeandeu** [comment]
34 mg available. logs since April 2016! 
Can i delete logs folder?

**Comment by michelem09** [comment]
No, you can delete the files inside not the directory

**Comment by watashimeandeu** [comment]
61mg now. Still not login.
I have an old 4gb memory card!
Any help to clean unnecessary data?
If not i have to put a larger sd card!

**Comment by michelem09** [comment]
If you have 61MB available should be sufficient to login, may be it's not that the problem.
Try `apt-get autoremove` and `apt-get autoclean`
But you should try login and look at logs.

**Comment by watashimeandeu** [comment]
80mg...
I have to change sd card.

ERROR - 2017-04-06 14:13:07 --> Redis server returned an error: ONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
ERROR - 2017-04-06 14:13:07 --> --- END CRON TASKS (3.38 secs) ---

**Comment by michelem09** [comment]
I'd like to suggest to start from scratch downloading the last Minera image https://getminera.com/download/latest
Then check the SD card space and do the resize if needed.
I'm going to close this because I don't think it's a systematic error.
