### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Ayo91** [michelem09/minera#162]
I try to access to the minera web interface and the browser shows this message...

<img width="1398" alt="screen" src="https://cloud.githubusercontent.com/assets/2479896/25592662/8dbd4f10-2eb1-11e7-9534-baf04abab28d.png">

However, I can access by ssh. The /minera/index.php/app/stats url shows this:
{
notloggedin: true
}

Any idea? Where are the error logs?

Thanks

**Comment by Ayo91** [comment]
I found a log file in this directory: /var/log/minera

This is the content (I change the .php extension to .txt): 

[log-2017-04-30.txt](https://github.com/michelem09/minera/files/968696/log-2017-04-30.txt)

**Comment by michelem09** [comment]
mmm for the error 500 you should check the web server logs.

For the errors in log check you have php-crypto installed, then please tell me how you installed Minera, did you install it manually? On what system?

**Comment by Ayo91** [comment]
I have installed Minera in a Rasberry pi B+ with the auto install process as you recommended (Image file v0.7.0). I downloaded the last version and then I upgraded by console

**Comment by michelem09** [comment]
So did you flash the SD card with the image file? Could you do this again without doing anything else after it?
And please on the current install check (and paste) the output of this command:

`dpkg -l | grep php`

**Comment by Ayo91** [comment]
Yeah I flashed the SD card with the last image file. Ok, I will do that. I have done it three times because Minera stopped working. This time I wanted to solve the issue because each time that I reinstall, I have to configure everyhing again.

Ok, after work I will paste here the result of the command.

Thanks

**Comment by Ayo91** [comment]
Hello. This is the screenshot of the command dpkg -l | grep php (before reinstall Minera again). 

![command](https://cloud.githubusercontent.com/assets/2479896/25641904/930b6c8a-2f8e-11e7-8349-9435597c8e84.png)

Any solution before reinstall Minera? Thanks

**Comment by michelem09** [comment]
That's really weird. Unfortunately you have to reinstall from the image. 
Then please update only the code with:

```
cd /var/www/minera
sudo git fetch --all && sudo git reset --hard origin/master
```

And let me know.
Thanks

**Comment by Ayo91** [comment]
With the reset everything works. Thanks so much!
