### ISSUE TITLE
Awesome font icon fix

### ISSUE THREAD

**Issue by tekcomm** [michelem09/minera#164]
Please add the following to fix the awesome fonts they are broke.
minera/views/include/header.php:

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="//fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css">

**Comment by michelem09** [comment]
Your message was truncated

**Comment by tekcomm** [comment]
Here is the diff fix on paste bin.
https://pastebin.com/StQgc9RL

**Comment by michelem09** [comment]
Why do you declare it twice?

**Comment by tekcomm** [comment]
Because I like to do things twice, The cdn can bounce. In my code I replaced it with cloudflare. I declare it twice because sometimes cdn have anti-spam detection that fubars stuff up and one will fail.

**Comment by tekcomm** [comment]
Here's why cloudflare and all the cdns anti dos causes  the script to
randomly fail.

**Comment by tekcomm** [comment]
Dump the files with wget and declare them once

**Comment by michelem09** [comment]
Yes probably it's the best solution keeping it local, I will work on this.

**Comment by michelem09** [comment]
Changed to local fonts ready for next release
