### ISSUE TITLE
Please change the following in the ubuntu script so it works. Php5 is depreciated. But there is a good  ppa of 5.6 

### ISSUE THREAD

**Issue by tekcomm** [michelem09/minera#166]
sudo apt-get purge `dpkg -l | grep php| awk '{print $2}' |tr "\n" " "`
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php5.6
sudo apt-get install php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml

And change the following.
install_minera_ubuntu.sh:
sudo apt-get install -y lighttpd php5.6-cgi redis-server git screen php5.6-cli php5.6-curl

upgrade_minera.sh:
apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y build-essential libtool libcurl4-openssl-dev libjansson-dev libudev-dev libncurses5-dev autoconf automake postfix redis-server git screen php5.6-cli php5.6-curl uthash-dev libmicrohttpd-dev libevent-dev libusb-1.0-0-dev libusb-dev shellinabox supervisor

minera-bin/src/bfgminer/ccan-upstream/Makefile-web:	php5.6 web/staticjunkcode.php junkcode/$* $* > $@
minera-bin/src/bfgminer/ccan-upstream/Makefile-web:	php5.6 web/staticall.php ccan/ junkcode/ $(WEBDIR) $(MODS) > $@
minera-bin/src/bfgminer/ccan-upstream/Makefile-web:	php5.6 web/staticupload.php > $@
minera-bin/src/bfgminer/ccan-upstream/Makefile-web:	php5.6 web/staticindex.php > $@
minera-bin/src/bfgminer/ccan-upstream/Makefile-web:	URLPREFIX=../`echo $* | tr -dc '/' | sed s',/,../,g'` php5.6 web/staticmoduleinfo.php `pwd`/ccan/$* $* > $@

install_minera.sh:
apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y build-essential libtool libcurl4-openssl-dev libjansson-dev libudev-dev libncurses5-dev autoconf automake postfix redis-server git screen php5.6-cli php5.6-curl php5.6-fpm php5.6-readline php5.6-json wicd-curses uthash-dev libmicrohttpd-dev libevent-dev libusb-1.0-0-dev libusb-dev shellinabox supervisor lighttpd

minera-bin/src/bfgminer/ccan-upstream/Makefile-web:	
URLPREFIX=../`echo $* | tr -dc '/' | sed s',/,../,g'` php5 web/staticmoduleinfo.php `pwd`/ccan/$* $* > $@
Dockerfile:RUN apt-get update && apt-get install -y lighttpd php5.6-cgi
Dockerfile:RUN apt-get install -y curl screen php5-cli php5.6-curl

**Comment by michelem09** [comment]
I have a new script for Ubuntu to run with PHP7.0 that's better then use PHP5 with some third party repo.
