### ISSUE TITLE
Minera as network dashboard

### ISSUE THREAD

**Issue by 9600-** [michelem09/minera#87]
Have you explored the option of using Minera as a dashboard for networked miners?  There are far too few options when it comes to a quality dashboard to monitor multiple cgminer instances over a network. 

Thoughts?

**Comment by nightrid3r** [comment]
@geopayme 

#! /bin/bash

sudo apt-get install -y lighttpd php5-cgi
sudo lighty-enable-mod fastcgi
sudo lighty-enable-mod fastcgi-php
sudo service lighttpd force-reload
sudo apt-get install -y redis-server git screen php5-cli php5-curl
cd /var/www
sudo git clone https://github.com/michelem09/minera
cd minera
sudo ./install_minera.sh
cd /var/www/minera
./build_miner.sh all
